version: '3.9'

services:
  web:
    build: .
    command: ["manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8030:8000"
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
